server:
  port: 8091

weixin:
  config:
    originalid: gh_1a91e3186657
    app-id: wx29ab5ca123cc2b04
    app-secret: 321a8dc971957ae5ea6f2d2ee811e681

logging:
  level:
    root: info
  config: classpath:logback-spring.xml